#!/usr/bin/make

########################################################################

# *** Fill out this information *** 

#  Project Name
PROJECT = leds_c
#  List of the objects files to be compiled/assembled
OBJECTS = main.o

# Selected compiler/architecture
ARCH = gcc/mbed
# Programming language for this project (C for C, CPP for C++)
LANGUAGE = C

# Path to the compiler and library
PATH := $(PATH):/home/users/marga/facu/6600/download/gcc-arm-none-eabi-4_6-2012q1/bin
LIB_BASE := ../../src

# Compiling options
DEBUG = -g
OPTIMIZATION = 0

########################################################################

# Include libmanyuc's Makefile to take care of the rest
include $(LIB_BASE)/Makefile

